id: A47407E57
title: Verses of Auspiciousness
type: translation
pechas:
- IBA6C26AA
- I1CC4510C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:07:53.717681
  last_modified_at: 2023-01-04 12:07:53.717692
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IBA6C26AA/FEE7: 18D9
  I1CC4510C/54DD: 18D9
